repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.27.0
    hooks:
    -   id: golangci-lint
